In [ ]:
import numpy as np

x = np.array([1,2,3]) # row vector
print(x.reshape((3,1))) #using reshape to convert to column vector

[[1]
 [2]
 [3]]


# matrix 

- 수치들의 N차원 배열 

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(np.arange(12).reshape((3,4))) #arrange to create a sequence of numbers and reshape to 3 rows and 4 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# tensor

- 차원이 셋이상인 객체들을 통칭해서 tensor라고 부른다 

## 차수 ( order )

- 텐서의 차수와 행렬의 차수는 다르다. 
- 3차원 텐서의 차수는 3
- 2차원 텐서의 차수는 2
- 1차원 텐서의 차수는 1
- 0차원(스칼라) 텐서의 차수는 0 

In [4]:
t = np.arange(36).reshape((3,3,4)) #arrange to create a sequence of numbers and reshape to 3 blocks, 3 rows and 4 columns
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [6]:
t = np.arange(48).reshape((4,3,4)) #arrange to create a sequence of numbers and reshape to 4 blocks, 3 rows and 4 columns
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [8]:
t = np.arange(24).reshape((4,2,3)) #arrange to create a sequence of numbers and reshape to 4 blocks, 2 rows and 3 columns
print(t)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [9]:
print(t[0]) #access the first block

[[0 1 2]
 [3 4 5]]


In [10]:
print(t[0,1]) #access the second row of the first block

[3 4 5]


In [12]:
print(t[0,1,2]) #access the third element of the second row of the first block


5


In [13]:
# 5 tensor is a 5-dimensional array. It can be created using the reshape function in numpy. For example, we can create a 5D tensor with shape (2, 3, 4, 5, 6) using the following code:

t = np.arange(720).reshape((2, 3, 4, 5, 6)) #arrange to create a sequence of numbers and reshape to 2 blocks, 3 rows, 4 columns, 5 depth and 6 channels
print(t)

[[[[[  0   1   2   3   4   5]
    [  6   7   8   9  10  11]
    [ 12  13  14  15  16  17]
    [ 18  19  20  21  22  23]
    [ 24  25  26  27  28  29]]

   [[ 30  31  32  33  34  35]
    [ 36  37  38  39  40  41]
    [ 42  43  44  45  46  47]
    [ 48  49  50  51  52  53]
    [ 54  55  56  57  58  59]]

   [[ 60  61  62  63  64  65]
    [ 66  67  68  69  70  71]
    [ 72  73  74  75  76  77]
    [ 78  79  80  81  82  83]
    [ 84  85  86  87  88  89]]

   [[ 90  91  92  93  94  95]
    [ 96  97  98  99 100 101]
    [102 103 104 105 106 107]
    [108 109 110 111 112 113]
    [114 115 116 117 118 119]]]


  [[[120 121 122 123 124 125]
    [126 127 128 129 130 131]
    [132 133 134 135 136 137]
    [138 139 140 141 142 143]
    [144 145 146 147 148 149]]

   [[150 151 152 153 154 155]
    [156 157 158 159 160 161]
    [162 163 164 165 166 167]
    [168 169 170 171 172 173]
    [174 175 176 177 178 179]]

   [[180 181 182 183 184 185]
    [186 187 188 189 190 191]
    [192 193 194 195 196 1

In [14]:
w = np.zeros((9,9,9,9,9)) #create a 5D tensor with shape (9, 9, 9, 9, 9) filled with zeros
print(w)

[[[[[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]]

   [[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]]

   [[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]]

   ...

   [[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]]

   [[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]]

   [[0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    [0. 0. 0. ... 0. 0. 0.]
    ...
    [0. 0.

In [15]:
t = np.array(42).reshape((1,1,1,1,1)) #create a 5D tensor with shape (1, 1, 1, 1, 1) filled with the value 42
print(t)

[[[[[42]]]]]


In [17]:
t.shape #check the shape of the tensor 

(1, 1, 1, 1, 1)

In [18]:
t[0,0,0,0,0] #access the only element in the tensor

np.int64(42)

In [19]:
t = np.array([[1,2,3],[4,5,6],[7,8,9]]) #create a 2D tensor with shape (3, 3) filled with the values from 1 to 9
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
w = t[np.newaxis,:,:] #add a new axis to the tensor to create a 3D tensor with shape (1, 3, 3)
print(w)

# 내부적으로는 파이썬의 None과 동일한 객체입니다. 따라서 t[None, :, :]라고 써도 똑같이 차원이 추가됩니다.

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
