In [ ]:
import numpy as np

x = np.array([1,2,3]) # row vector
print(x.reshape((3,1))) #using reshape to convert to column vector

[[1]
 [2]
 [3]]


# matrix 

- 수치들의 N차원 배열 

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(np.arange(12).reshape((3,4))) #arrange to create a sequence of numbers and reshape to 3 rows and 4 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
