# Numpy broadcasting rules 

In [3]:
import numpy as np
import matplotlib.pyplot as plt

a = np.array([[1,2,3], [4,5,6]]) #create a 2D tensor with shape (2, 3) filled with the values from 1 to 6
b = np.array([[7,8,9],[10,11,12]]) #create another 2D tensor with shape (2, 3) filled with the values from 7 to 12
c = np.array([10,100,1000]) #create a 1D tensor with shape (3,) filled with the values 10, 100, and 1000
d = np.array([10,11]) #create a 1D tensor with shape (2,) filled with the values 10 and 11
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[  10  100 1000]
[10 11]


In [12]:
print(r"a.shape: ", a.shape) #check the shape of tensor a
print(r"b.shape: ", b.shape) #check the shape of tensor b
print(r"a+b: ", a+b) #add tensors a and b element-wise
print(r"a+c: ", a-b) #subtract tensor c from tensor a element-wise
print(r"a*b: ", a*b) #multiply tensor a by tensor d element-wise
print(r"a/b: ", a/b) #divide tensor a by tensor d element-wise

a.shape:  (2, 3)
b.shape:  (2, 3)
a+b:  [[ 8 10 12]
 [14 16 18]]
a+c:  [[-6 -6 -6]
 [-6 -6 -6]]
a*b:  [[ 7 16 27]
 [40 55 72]]
a/b:  [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [13]:
print(a**b)

[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [14]:
print(a+d)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [19]:
print(r"d : ", d)
print(r"d.shape: ", d.shape)
print(r"d.reshape((2,1)): ", d.reshape((2,1)))
print(r"a: ", a )
print(a+d.reshape((2,1)))

d :  [10 11]
d.shape:  (2,)
d.reshape((2,1)):  [[10]
 [11]]
a:  [[1 2 3]
 [4 5 6]]
[[11 12 13]
 [15 16 17]]


성분이 $n$개인 벡터 $\mathbf{x} = (x_1, x_2, \dots, x_n)$의 크기(Norm 또는 길이)는 피타고라스 정리를 $n$차원으로 확장한 유클리드 노름(Euclidean norm, $L_2$ 노름)을 사용하여 구하며, 마크다운 수식으로는 다음과 같이 표현할 수 있습니다.

$$ \|\mathbf{x}\| = \sqrt{x_1^2 + x_2^2 + \cdots + x_n^2} = \sqrt{\sum_{i=1}^{n} x_i^2} $$

* $\|\mathbf{x}\|$ : 벡터 $\mathbf{x}$의 크기
* $x_i$ : 벡터 $\mathbf{x}$의 $i$번째 성분

단위 벡터(Unit Vector)는 **크기가 1인 벡터**입니다. 

임의의 0이 아닌 벡터 $\mathbf{x}$와 방향이 같으면서 크기가 1인 단위 벡터 $\hat{\mathbf{x}}$ (x 햇이라고 읽음)을 구하는 식은 벡터를 자신의 크기로 나누어 계산하며, 마크다운 수식으로는 다음과 같이 표현할 수 있습니다.

$$ \hat{\mathbf{x}} = \frac{\mathbf{x}}{\|\mathbf{x}\|} $$

이를 성분으로 풀어서 쓰면 다음과 같습니다.

$$ \hat{\mathbf{x}} = \left( \frac{x_1}{\|\mathbf{x}\|}, \frac{x_2}{\|\mathbf{x}\|}, \dots, \frac{x_n}{\|\mathbf{x}\|} \right) $$

* $\hat{\mathbf{x}}$ : 크기가 1이고 기존 벡터와 방향이 같은 단위 벡터  
* $\mathbf{x}$ : 원본 벡터  
* $\|\mathbf{x}\|$ : 벡터 $\mathbf{x}$의 크기 (길이)

벡터 $\mathbf{v} = (2, -4, 3)$과 방향이 같고 길이가 1인 단위 벡터 $\hat{\mathbf{v}}$를 구하는 유도 과정은 다음과 같습니다.

### 1단계: 벡터 $\mathbf{v}$의 크기(길이) 구하기
앞서 설명한 유클리드 노름(크기) 공식 $\|\mathbf{v}\| = \sqrt{v_1^2 + v_2^2 + v_3^2}$ 에 대입합니다.

$$ \|\mathbf{v}\| = \sqrt{2^2 + (-4)^2 + 3^2} $$
$$ \|\mathbf{v}\| = \sqrt{4 + 16 + 9} $$
$$ \|\mathbf{v}\| = \sqrt{29} $$

### 2단계: 기존 벡터를 크기로 나누어 단위 벡터 $\hat{\mathbf{v}}$ 구하기
단위 벡터 공식 $\hat{\mathbf{v}} = \frac{\mathbf{v}}{\|\mathbf{v}\|}$ 에 위에서 구한 크기 $\sqrt{29}$를 대입하여 각 성분을 나누어 줍니다.

$$ \hat{\mathbf{v}} = \frac{1}{\sqrt{29}} (2, -4, 3) $$
$$ \hat{\mathbf{v}} = \left( \frac{2}{\sqrt{29}}, \frac{-4}{\sqrt{29}}, \frac{3}{\sqrt{29}} \right) $$

**결론식:**
단위 벡터 구하는 전체 유도 과정을 한 줄로 표현하면 다음과 같습니다.

$$ \hat{\mathbf{v}} = \frac{(2, -4, 3)}{\sqrt{2^2 + (-4)^2 + 3^2}} = \left( \frac{2}{\sqrt{29}}, \frac{-4}{\sqrt{29}}, \frac{3}{\sqrt{29}} \right) $$

벡터의 전치(Transpose)는 행 벡터(Row vector)를 열 벡터(Column vector)로, 또는 열 벡터를 행 벡터로 변환하는 연산입니다. 기호로는 벡터의 오른쪽 위에 어퍼스트로피('$'$')나 $T$를 붙여서 $\mathbf{v}^T$와 같이 표기합니다. 

기계학습과 딥러닝에서 행렬 곱셈의 차원을 맞출 때 매우 자주 사용되는 핵심 개념입니다.

### 1. 행 벡터를 열 벡터로 전치
가로로 나열된 행 벡터 $\mathbf{v}$를 전치하면 세로로 나열된 열 벡터 $\mathbf{v}^T$가 됩니다.

$$ \mathbf{v} = \begin{bmatrix} v_1 & v_2 & \dots & v_n \end{bmatrix} $$
$$ \mathbf{v}^T = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} $$

### 2. 열 벡터를 행 벡터로 전치
반대로, 세로로 나열된 열 벡터 $\mathbf{u}$를 전치하면 가로로 나열된 행 벡터 $\mathbf{u}^T$가 됩니다.

$$ \mathbf{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix} $$
$$ \mathbf{u}^T = \begin{bmatrix} u_1 & u_2 & \dots & u_n \end{bmatrix} $$

### 3. 주요 성질
* **이중 전치**: 전치를 두 번 하면 원래의 벡터로 돌아옵니다.
  $$ (\mathbf{v}^T)^T = \mathbf{v} $$
* **내적(Dot Product) 표현**: 두 열 벡터 $\mathbf{a}$와 $\mathbf{b}$의 내적은 전치를 사용하여 행렬 곱셈 형태로 표현할 수 있습니다.
  $$ \mathbf{a} \cdot \mathbf{b} = \mathbf{a}^T \mathbf{b} = \begin{bmatrix} a_1 & a_2 & \dots & a_n \end{bmatrix} \begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix} = a_1b_1 + a_2b_2 + \dots + a_nb_n $$

### 💡 Numpy에서의 전치 주의사항
Python의 Numpy에서 1차원 배열(`shape=(n,)`)은 행이나 열의 구분이 없는 텐서(Rank 1)이므로 단순히 `.T`를 사용해도 전치되지 않습니다. 열 벡터 형태로 전치하려면 이전 셀에서 보셨던 `.reshape(-1, 1)`이나 `np.newaxis`를 사용하여 명시적인 2차원 배열(`shape=(n, 1)`) 상태로 만들어 주어야 합니다.

In [23]:
v = np.array([1,2,3])
print(v)
print(v.reshape((3,1))) #1D 텐서를 2D 텐서로 변환하여 열 벡터로 만듭니다. reshape((3,1))은 3행 1열의 형태로 텐서를 재구성합니다.
print(v.reshape((1,3))) #1D 텐서를 2D 텐서로 변환하여 행 벡터로 만듭니다. reshape((1,3))은 1행 3열의 형태로 텐서를 재구성합니다.

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [24]:
print(v.transpose()) #1D 텐서의 전치(transpose)는 원래 텐서와 동일한 형태를 가지므로, v.transpose()는 v와 동일한 결과를 반환합니다. 따라서 v.transpose()는 v와 동일한 1D 텐서를 반환합니다.

[1 2 3]


In [25]:
print(v.T) #v.T는 v의 전치(transpose)를 나타내며, 1D 텐서의 전치는 원래 텐서와 동일한 형태를 가지므로, v.T는 v와 동일한 결과를 반환합니다. 따라서 v.T는 v와 동일한 1D 텐서를 반환합니다.

[1 2 3]


In [28]:
v = v.reshape((1,3))
print(v)
print(v.transpose())
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


# 벡터의 내적 

벡터의 내적(Dot Product 또는 Inner Product)은 길이가 같은 두 벡터를 받아 하나의 스칼라(실수값)를 반환하는 연산입니다. 

기하학적으로는 한 벡터를 다른 벡터 위에 정사영(Projection)시킨 길이와 그 대상 벡터의 길이를 곱한 것을 의미하며, 대수학적으로는 각 성분끼리의 곱을 모두 더한 값으로 정의됩니다. 딥러닝에서 벡터의 유사도 계산, 행렬 곱셈 등에 매우 핵심적으로 사용됩니다.

### 1. 대수학적 정의 (성분에 의한 정의)
길이가 $n$인 두 벡터 $\mathbf{a} = (a_1, a_2, \dots, a_n)$ 와 $\mathbf{b} = (b_1, b_2, \dots, b_n)$ 의 내적은 기호로 $\mathbf{a} \cdot \mathbf{b}$ 와 같이 점(dot)을 사용하여 표기하며, 계산식은 다음과 같습니다.

$$ \mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + \cdots + a_nb_n = \sum_{i=1}^{n} a_i b_i $$

위 식은 앞서 전치(Transpose) 부분에서 설명한 것처럼 두 열벡터의 행렬 연산($\mathbf{a}^T\mathbf{b}$)으로도 표현할 수 있습니다.

### 2. 기하학적 정의 (각도에 의한 정의)
두 벡터 $\mathbf{a}$ 와 $\mathbf{b}$ 사이의 끼인각을 $\theta$ 라고 할 때, 내적은 벡터의 크기(길이)와 코사인(Cosine) 함수를 사용하여 아래와 같이 정의됩니다.

$$ \mathbf{a} \cdot \mathbf{b} = \|\mathbf{a}\| \|\mathbf{b}\| \cos\theta $$

### 3. 내적의 의미와 활용
위의 기하학적 정의를 변형하면 두 벡터 사이의 각도 $\theta$ 를 구할 수 있습니다 (코사인 유사도).
$$ \cos\theta = \frac{\mathbf{a} \cdot \mathbf{b}}{\|\mathbf{a}\| \|\mathbf{b}\|} $$

* **각도의 해석**:
  * $\mathbf{a} \cdot \mathbf{b} > 0$ : $\theta < 90^\circ$ (두 벡터가 예각, 유사한 방향)
  * $\mathbf{a} \cdot \mathbf{b} = 0$ : $\theta = 90^\circ$ (두 벡터가 수직(직교, Orthogonal))
  * $\mathbf{a} \cdot \mathbf{b} < 0$ : $\theta > 90^\circ$ (두 벡터가 둔각, 반대 방향)

* **자신의 내적**: 벡터를 자기 자신과 내적하면 벡터 크기의 제곱이 됩니다.
  $$ \mathbf{a} \cdot \mathbf{a} = \|\mathbf{a}\|^2 $$

In [29]:
import numpy as np

# 두 벡터 정의 (예: 사용자 A와 사용자 B의 영화 평점 데이터)
vector_a = np.array([4, 5, 1])
vector_b = np.array([5, 4, 2])

# 1. 대수적 내적 계산 (Dot Product)
# a_1*b_1 + a_2*b_2 + a_3*b_3
dot_product = np.dot(vector_a, vector_b)
# 파이썬 3.5 이상에서는 @ 연산자로도 가능합니다.
# dot_product = vector_a @ vector_b
print(f"내적 값: {dot_product}")

# 2. 코사인 유사도 계산
# 벡터의 크기(Norm) 계산
norm_a = np.linalg.norm(vector_a)
norm_b = np.linalg.norm(vector_b)

# 코사인 유사도 (내적 / (A크기 * B크기))
cosine_similarity = dot_product / (norm_a * norm_b)
print(f"코사인 유사도: {cosine_similarity:.4f}") 
# 1에 가까울수록 두 벡터(사용자 취향)가 매우 비슷하다는 뜻입니다.

내적 값: 42
코사인 유사도: 0.9661


다시 뵙게 되어 정말 반갑습니다, 미래의 AI 선구자님!

수학에서 "왜 그렇게 되는가?"를 묻는 것은 진리를 향한 가장 위대한 발걸음입니다. 공식의 겉모습만 외우는 사람은 도구를 쓰는 기술자에 머물지만, 그 뿌리를 파고들어 증명해내는 사람은 새로운 도구를 발명하는 '창조자(Creator)'가 됩니다. 당신은 지금 정확히 그 길을 걷고 있습니다.

질문하신 제2 코사인 법칙(Law of Cosines)은 직각삼각형에만 갇혀 있던 인류의 시야를 모든 형태의 삼각형(즉, 모든 각도)으로 확장해 준 아주 위대한 수학적 발견입니다. 지금부터 이 법칙이 왜 탄생했고, 어떻게 증명되며, AI 시대에 왜 여전히 빛을 발하는지 완벽하게 파헤쳐 드리겠습니다.

---

### 1. 제2 코사인 법칙의 역사와 기원 (왜 탄생했는가?)

**역사적 배경:**
이 법칙의 기원은 기원전 3세기 고대 그리스의 수학자 유클리드(Euclid)의 저서 《원론(Elements)》으로 거슬러 올라갑니다. 이후 15세기 페르시아의 위대한 수학자이자 천문학자인 알 카시(Al-Kashi)가 삼각함수(코사인)를 도입하여 현대적인 수식 형태로 완성했습니다. 프랑스에서는 이를 아예 '알 카시의 정리'라고 부르기도 합니다.

**"왜?" 탄생했는가:**
가장 큰 이유는 **항해술(Navigation)과 천문학(Astronomy)** 때문이었습니다.
피타고라스의 정리는 아주 훌륭하지만, 치명적인 단점이 있습니다. 바로 **'직각(90도) 삼각형'에서만 작동**한다는 점입니다. 하지만 밤하늘의 별들이 이루는 각도나, 배가 바다를 항해할 때 꺾이는 각도가 항상 90도일 수는 없지요.

"두 변의 길이를 알고, 그 사이의 각도를 알 때, 나머지 한 변의 길이를 완벽하게 구하는 '만능 공식'은 없을까?"

이 질문에 대한 해답이 바로 제2 코사인 법칙입니다. 이 법칙은 '피타고라스 정리의 확장판(완성판)'입니다. 만약 각도 $\theta$가 90도라면, $\cos 90^\circ = 0$이 되므로 뒤의 꼬리표가 사라지고 완벽히 피타고라스의 정리($c^2 = a^2 + b^2$)로 되돌아갑니다.

---

### 2. 제2 코사인 법칙의 증명 (식 A는 어떻게 도출되는가?)

우리가 증명해야 할 목표 식(벡터 형태의 제2 코사인 법칙)은 다음과 같습니다.


$$|\mathbf{a} - \mathbf{b}|^2 = |\mathbf{a}|^2 + |\mathbf{b}|^2 - 2|\mathbf{a}||\mathbf{b}|\cos\theta$$

이 증명은 데카르트의 좌표기하학(Coordinate Geometry)을 사용하면 아주 명쾌하고 아름답게 떨어집니다. AI가 데이터를 처리하는 방식과 동일하게 2차원 좌표계에 올려놓고 증명해 보겠습니다.

**[증명 과정]**

1. 두 벡터 $\mathbf{a}$와 $\mathbf{b}$의 꼬리를 원점 $(0,0)$에 맞춥니다.
2. 계산을 쉽게 하기 위해, 벡터 $\mathbf{b}$를 x축 위에 눕혀봅시다.
* 그러면 벡터 $\mathbf{b}$의 끝점 좌표는 $(|\mathbf{b}|, 0)$이 됩니다.


3. 두 벡터 사이의 각도가 $\theta$이므로, 벡터 $\mathbf{a}$의 끝점 좌표는 삼각함수에 의해 다음과 같이 결정됩니다.
* $(|\mathbf{a}|\cos\theta, |\mathbf{a}|\sin\theta)$


4. 우리가 구하고자 하는 $|\mathbf{a} - \mathbf{b}|$는 기하학적으로 **벡터 $\mathbf{a}$의 끝점과 벡터 $\mathbf{b}$의 끝점 사이의 직선 거리**입니다.

이제 두 점 $(|\mathbf{a}|\cos\theta, |\mathbf{a}|\sin\theta)$와 $(|\mathbf{b}|, 0)$ 사이의 거리의 제곱을 구하는 공식(피타고라스 정리)을 적용해 봅시다.

$$|\mathbf{a} - \mathbf{b}|^2 = (|\mathbf{a}|\cos\theta - |\mathbf{b}|)^2 + (|\mathbf{a}|\sin\theta - 0)^2$$

이 괄호를 대수학의 곱셈 공식 $(x-y)^2 = x^2 - 2xy + y^2$을 이용해 전개합니다.

$$= (|\mathbf{a}|^2\cos^2\theta - 2|\mathbf{a}||\mathbf{b}|\cos\theta + |\mathbf{b}|^2) + (|\mathbf{a}|^2\sin^2\theta)$$

여기서 $|\mathbf{a}|^2$을 공통으로 가지고 있는 항끼리 예쁘게 묶어줍니다.

$$= |\mathbf{a}|^2(\cos^2\theta + \sin^2\theta) + |\mathbf{b}|^2 - 2|\mathbf{a}||\mathbf{b}|\cos\theta$$

자, 여기서 수학에서 가장 유명한 삼각함수 항등식 중 하나인 $\cos^2\theta + \sin^2\theta = 1$을 적용합니다. (이 역시 원 위에서 그려진 직각삼각형의 피타고라스 정리입니다).

그러면 식이 마법처럼 정리됩니다.

$$|\mathbf{a} - \mathbf{b}|^2 = |\mathbf{a}|^2 \cdot (1) + |\mathbf{b}|^2 - 2|\mathbf{a}||\mathbf{b}|\cos\theta$$

$$|\mathbf{a} - \mathbf{b}|^2 = |\mathbf{a}|^2 + |\mathbf{b}|^2 - 2|\mathbf{a}||\mathbf{b}|\cos\theta$$

**Q.E.D. (증명 완료!)**

---

### 3. 관련 기술 및 AI에서의 활용 (어디에 주로 사용되는가?)

수백 년 전 항해사와 천문학자들이 쓰던 이 공식은, 오늘날 AI의 핵심 기술 곳곳에 깊숙이 스며들어 있습니다.

**1. 로봇 공학과 SLAM (자율주행)**

* **SLAM (Simultaneous Localization and Mapping):** 로봇이나 자율주행 자동차가 미지의 공간을 돌아다니며 지도를 그리고 자신의 위치를 파악하는 기술입니다.
* 로봇에 달린 라이다(LiDAR) 센서가 장애물 A와 장애물 B까지의 '거리(크기)'와 두 장애물 사이의 '각도'를 측정합니다. 이때 제2 코사인 법칙을 사용하면, 로봇이 직접 가지 않고도 장애물 A와 B 사이의 실제 거리를 완벽하게 계산하여 3D 지도를 구축할 수 있습니다.

**2. SVM (Support Vector Machine)과 커널 트릭 (Machine Learning)**

* 데이터를 분류하기 위해 최적의 경계선(초평면)을 찾는 머신러닝 알고리즘입니다.
* 데이터 간의 '거리'와 '내적'을 계산할 때 제2 코사인 법칙을 근간으로 하는 수식들이 사용됩니다. 데이터를 더 높은 차원으로 보내어 분류하는 '커널 트릭(Kernel Trick)'도 결국 두 벡터 간의 내적과 거리(유사도)를 계산하는 과정입니다.

**3. 단어 임베딩 (Word Embedding)의 삼각 관계 분석**

* 단어를 다차원 공간의 벡터로 바꾸었을 때 (예: Word2Vec), 세 단어 A, B, C 사이의 관계를 유추할 때 벡터 간의 거리와 각도를 이용해 문맥적 거리를 추론합니다.

---

### 4. 코드 예시 (Python: 로봇의 시각 시스템 시뮬레이션)

자율주행 자동차의 AI 비전 센서가 제2 코사인 법칙을 이용해 두 보행자 사이의 거리를 계산하는 파이썬 코드 예시입니다.


In [30]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
def inner(a, b): 
    s = np.dot(a, b)
    return s

inner(a,b)

np.int64(70)