### 1. 외적(Cross Product)의 정의
외적은 3차원 공간($\mathbb{R}^3$)에서 두 벡터를 연산하여 **두 벡터에 모두 수직인 새로운 '벡터'**를 얻는 연산입니다. 내적이 스칼라(실수)를 반환하는 것과 달리, 외적은 벡터를 반환하므로 '벡터곱(Vector Product)'이라고도 부릅니다.
* **크기**: 두 벡터가 가리키는 평행사변형의 넓이입니다. ($\|\mathbf{a} \times \mathbf{b}\| = \|\mathbf{a}\| \|\mathbf{b}\| \sin\theta$)
* **방향**: 오른손 법칙(Right-hand rule)에 의해 벡터 $\mathbf{a}$에서 $\mathbf{b}$ 쪽으로 오른손 네 손가락을 감아쥘 때, 엄지손가락이 가리키는 방향입니다.

### 2. 외적의 역사
외적과 내적의 개념은 아일랜드의 수학자 **윌리엄 로언 해밀턴(William Rowan Hamilton)**이 1843년에 창안한 **사원수(Quaternion)** 체계에서 기원했습니다.
하지만 사원수는 물리학이나 공학에 바로 적용하기에 계산이 너무 길고 복잡했습니다. 19세기 후반, 미국의 **조사이어 윌러드 기브스(Josiah Willard Gibbs)**와 영국의 **올리버 헤비사이드(Oliver Heaviside)**가 사원수에서 실수부와 허수부를 분해하여 3차원 공간에 훨씬 사용하기 편리한 '내적(스칼라곱)'과 '외적(벡터곱)'의 현대적인 표기법을 확립했습니다. 이는 맥스웰의 전자기학 방정식을 단 몇 줄로 단순화시키는 데 일조하며 널리 퍼지게 되었습니다.

### 3. 외적의 수식과 직교성 증명
두 3차원 벡터 $\mathbf{a} = (a_1, a_2, a_3)$와 $\mathbf{b} = (b_1, b_2, b_3)$의 외적은 행렬의 행렬식을 이용하여 다음과 같이 정의됩니다. 기본 공간의 단위 벡터를 각각 $\mathbf{i}(x축), \mathbf{j}(y축), \mathbf{k}(z축)$라고 할 때:

$$ 
\mathbf{a} \times \mathbf{b} = \det \begin{bmatrix} \mathbf{i} & \mathbf{j} & \mathbf{k} \\ a_1 & a_2 & a_3 \\ b_1 & b_2 & b_3 \end{bmatrix} 
$$
$$ 
= (a_2 b_3 - a_3 b_2)\mathbf{i} - (a_1 b_3 - a_3 b_1)\mathbf{j} + (a_1 b_2 - a_2 b_1)\mathbf{k} 
$$

**[증명] 외적 결과 벡터가 정말 두 벡터와 수직일까?**
수직인지 확인하려면 외적 결과 $\mathbf{a} \times \mathbf{b}$와 원래 벡터 $\mathbf{a}$ (또는 $\mathbf{b}$)의 **내적이 0**이 되는지 확인하면 됩니다. 즉, $(\mathbf{a} \times \mathbf{b}) \cdot \mathbf{a} = 0$ 임을 증명합니다.

$$ (\mathbf{a} \times \mathbf{b}) \cdot \mathbf{a} = (a_2 b_3 - a_3 b_2)a_1 - (a_1 b_3 - a_3 b_1)a_2 + (a_1 b_2 - a_2 b_1)a_3 $$
$$ = a_1 a_2 b_3 - a_1 a_3 b_2 - a_1 a_2 b_3 + a_2 a_3 b_1 + a_1 a_3 b_2 - a_2 a_3 b_1 $$
모든 항이 양수/음수 짝을 이루어 서로 완벽히 상쇄됩니다.
$$ = 0 $$
$\mathbf{b}$에 대해서도 동일한 원리로 0이 되므로, 외적으로 생성된 벡터는 두 벡터 평면과 완전히 수직(직교)함을 알 수 있습니다.

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(f"np.dot(a,b)={np.dot(a,b)}")
print(f"np.inner(a,b)={np.inner(a,b)}")
print(f"a.dot(b)={a.dot(b)}")
print(f"a @ b={a @ b}")
print(f"np.sum(a*b)={np.sum(a*b)}")
print(f"np.outer(a,b)={np.outer(a,b)}")


np.dot(a,b)=70
np.inner(a,b)=70
a.dot(b)=70
a @ b=70
np.sum(a*b)=70
np.outer(a,b)=[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]
