드디어 올 것이 왔군요! 선형대수학의 대미를 장식하는 궁극의 보스이자, 현대 AI의 데이터 압축과 검색 엔진의 뼈대를 이루는 '고윳값(Eigenvalue)'과 '고유벡터(Eigenvector)'의 세계에 오신 것을 환영합니다.

앞선 여정에서 우리는 행렬이 공간을 무자비하게 찌그러뜨리고 회전시키는 '사상(Mapping)'이라는 것을 배웠습니다. 그렇다면 수학자들은 자연스럽게 이런 질문을 던지게 됩니다.
**"공간이 그렇게 혼란스럽게 뒤틀리는데, 그 와중에도 절대 방향이 변하지 않는 줏대 있는 선(축)이 존재할까?"**

이 질문에 대한 완벽한 해답이 바로 고유벡터입니다. 왜 이 개념이 탄생했고, 이전 시간에 배운 '행렬식(Determinant)'과 어떻게 소름 돋게 연결되는지 가우스의 시선으로 완벽히 해부해 드리겠습니다.

---

## 1. 역사적 배경과 용어의 의미 (Why & What)

이 개념은 18세기 레온하르트 오일러(Leonhard Euler)가 강체의 회전 운동을 연구하면서 '흔들리지 않는 회전의 중심축(Principal Axis)'을 찾기 위해 처음 고안했습니다. 이후 20세기 초, 위대한 수학자 다비트 힐베르트(David Hilbert)가 이 특별한 값들에 독일어로 '고유한, 본질적인, 특징적인'을 뜻하는 Eigen(아이겐)이라는 접두사를 붙이면서 오늘날의 이름이 완성되었습니다.

* **고유벡터 (Eigenvector, $v$):** 행렬 $A$에 의해 변환(Mapping)되더라도, **방향은 절대 바뀌지 않고 오직 길이만 늘어나거나 줄어드는** 공간 내의 아주 특별하고 고집스러운 벡터(축)입니다.
* **고윳값 (Eigenvalue, $\lambda$):** 그 고유벡터가 변환 후 원래 길이의 **몇 배($\lambda$ 배)가 되었는지**를 나타내는 배율(스칼라 값)입니다.

---

## 2. 수학적 정의와 소름 돋는 증명 과정

고유벡터와 고윳값의 관계를 수학적으로 나타내면, 선형대수학에서 가장 아름답고 유명한 다음 방정식이 됩니다.

$$Av = \lambda v$$

* **좌변 ($Av$):** 행렬 $A$가 벡터 $v$를 복잡하게 공간 변환시킨 결과입니다.
* **우변 ($\lambda v$):** 단순히 원래 벡터 $v$에 숫자 $\lambda$를 곱해 길이를 늘이거나 줄인 결과입니다.

이 두 결과가 완벽하게 같다는 것은, "행렬의 복잡한 변환이, 이 특정 벡터($v$)에게만큼은 단순한 스칼라 곱셈(길이 변화)으로 작용한다"는 뜻입니다.

### 어떻게 고유벡터를 찾을 것인가? (증명과 유도)

방정식을 풀어봅시다. 우변의 항을 왼쪽으로 넘기면 다음과 같이 됩니다.


$$Av - \lambda v = \mathbf{0}$$

벡터 $v$로 묶어내고 싶지만, $A$는 행렬이고 $\lambda$는 단순한 숫자라서 크기가 맞지 않아 묶을 수 없습니다. 그래서 어떤 벡터든 그대로 반환해 주는 단위행렬 $I$ (크기는 1과 같은 역할)를 $\lambda$ 옆에 슬쩍 끼워 넣습니다.


$$(A - \lambda I)v = \mathbf{0}$$

자, 이제 아주 중요한 순간입니다. 이 방정식이 성립하려면 두 가지 경우 중 하나여야 합니다.

1. **$v = \mathbf{0}$ 인 경우:** 벡터가 점(원점)이라면 방향 자체가 없으므로 아무 의미가 없습니다. 수학자들은 이를 '자명한 해(Trivial Solution)'라 부르며 취급하지 않습니다.
2. **$v \neq \mathbf{0}$ 인 경우:** 0이 아닌 고유벡터가 존재하려면, 행렬 $(A - \lambda I)$가 어떤 영벡터가 아닌 벡터를 영벡터($\mathbf{0}$)로 찌그러뜨려야 합니다.

이전 시간에 제가 무엇이라고 했는지 기억하시나요? "어떤 행렬이 2차원 평면을 1차원 선이나 점으로 완전히 찌그러뜨려(Collapse) 붕괴시킬 때, 그 행렬식(Determinant)은 0이 된다"고 했습니다.

즉, 의미 있는 고유벡터 $v$가 존재하기 위한 절대 조건은 새로운 행렬 $(A - \lambda I)$의 행렬식이 0이 되어야 한다는 것입니다. 이를 특성 방정식(Characteristic Equation)이라고 부릅니다.

$$\det(A - \lambda I) = 0$$

우리는 이 방정식을 통해 먼저 고윳값 $\lambda$를 찾고, 그 $\lambda$를 다시 식에 대입하여 방향을 유지하는 고유벡터 $v$를 찾아냅니다.

---

## 3. 현대 AI 기술에서의 핵심 활용 (확장성)

고윳값과 고유벡터는 시스템의 '본질'을 찾아내는 역할을 하므로, 현대 컴퓨터 공학과 AI에서 세상을 바꾸는 알고리즘들을 탄생시켰습니다.

1. **주성분 분석 (PCA, Principal Component Analysis):**
수천 개의 차원(특징)을 가진 빅데이터에서 가장 중요한 정보가 분포된 축을 찾을 때 사용됩니다. 데이터의 분산(공분산 행렬)을 계산한 뒤 고유벡터를 찾으면, 그것이 바로 데이터가 가장 넓게 퍼져 있는 '주요 축'이 됩니다. 고윳값이 큰 순서대로 축을 몇 개만 남기면, 정보 손실을 최소화하면서 고차원 데이터를 2차원이나 3차원으로 압축(차원 축소)할 수 있습니다.
2. **구글 페이지랭크 (Google PageRank):**
초기 구글 검색 엔진이 웹페이지의 순위를 매기던 방법의 본질은, 전 세계 웹페이지들의 링크 관계를 거대한 행렬(Markov Transition Matrix)로 만든 뒤, **고윳값이 1인 고유벡터**를 찾는 것이었습니다. 이 고유벡터의 각 원소 값이 바로 해당 웹페이지가 검색 상단에 노출될 '확률(권위)'이 됩니다.
3. **그래프 신경망 (Graph Neural Networks, GNN):**
최근 AI의 트렌드인 분자 구조 예측, 소셜 네트워크 분석 등에서 노드 간의 관계를 분석하는 '스펙트럴 그래프 이론(Spectral Graph Theory)'의 밑바탕이 바로 인접 행렬의 고윳값 분해입니다.

---

## 4. 파이토치(PyTorch) 코드 예시

PyTorch의 선형대수 모듈(`torch.linalg`)을 사용하면 복잡한 특성 방정식을 풀지 않아도 단 한 줄의 코드로 고윳값과 고유벡터를 추출할 수 있습니다.


In [ ]:
import torch

# 1. 2x2 정방행렬 A 정의 (예: 데이터의 변환을 나타내는 행렬)
A = torch.tensor([[4.0, 2.0],
                  [1.0, 3.0]], dtype=torch.float32)

# 2. 고윳값(eigenvalues)과 고유벡터(eigenvectors) 계산
# PyTorch는 복소수 형태의 결과가 나올 수 있어 보통 complex 텐서로 반환하지만
# 여기서는 편의상 실수부만 추출하여 확인합니다.
eigenvalues, eigenvectors = torch.linalg.eig(A)
eigenvalues = eigenvalues.real
eigenvectors = eigenvectors.real

print("=== 행렬 A ===")
print(A)

print("\n=== 고윳값 (Eigenvalues, λ) ===")
# 예상 결과: [5.0, 2.0]
print(eigenvalues)

print("\n=== 고유벡터 (Eigenvectors, v) ===")
# 열(Column) 벡터들이 각각의 고윳값에 대응하는 고유벡터입니다.
# 첫 번째 열이 λ=5에 대한 고유벡터, 두 번째 열이 λ=2에 대한 고유벡터
print(eigenvectors)

# 3. 증명: A * v = λ * v 가 정말 성립하는지 확인
lambda_1 = eigenvalues[0]
v_1 = eigenvectors[:, 0].unsqueeze(1) # 첫 번째 고유벡터 추출

left_side = torch.matmul(A, v_1)       # A * v
right_side = lambda_1 * v_1            # λ * v

print("\n=== 검증: A*v 와 λ*v 비교 ===")
print(f"A * v  :\n{left_side}")
print(f"λ * v :\n{right_side}")
# 두 결과가 수학적 오차 내에서 완벽히 일치함을 확인할 수 있습니다.


=== 행렬 A ===
tensor([[4., 2.],
        [1., 3.]])

=== 고윳값 (Eigenvalues, λ) ===
tensor([5.0000, 2.0000])

=== 고유벡터 (Eigenvectors, v) ===
tensor([[ 0.8944, -0.7071],
        [ 0.4472,  0.7071]])

=== 검증: A*v 와 λ*v 비교 ===
A * v  :
tensor([[4.4721],
        [2.2361]])
λ * v :
tensor([[4.4721],
        [2.2361]])


# 고윳값과 고유벡터의 역사와 증명 과정

---

## 1. 역사와 탄생 배경: "흔들리지 않는 회전축을 찾아서" (Why)

고윳값과 고유벡터의 개념은 **천체 물리학**과 **역학(Mechanics)**의 실용적인 문제를 해결하는 과정에서 태어났습니다.

### (1) 레온하르트 오일러와 강체의 회전 (1751년)
위대한 수학자 **레온하르트 오일러(Leonhard Euler)**는 '강체(형태가 변하지 않는 단단한 물체)'가 3차원 공간에서 회전 운동을 할 때의 움직임을 관찰하고 있었습니다. 
물체가 아무리 복잡하게 뱅글뱅글 돌아가며 위치가 변하더라도, **"그 무질서한 회전 속에서도 절대 방향이 바뀌지 않는 유일한 가상의 중심축"**이 존재해야 함을 깨달았습니다. 오일러가 찾고자 했던 이 '고정된 중심축'이 인류 역사상 최초로 발견된 **고유벡터**였습니다.

### (2) 조셉-루이 라그랑주와 행성 궤도의 안정성 (1780년대)
정밀한 천체 관측이 이루어지면서, 태양계 행성들이 서로 중력을 주고받음에도 불구하고 왜 궤도가 붕괴하지 않고 안정적으로 도는지가 수학계의 큰 화두였습니다. **라그랑주(Lagrange)**는 여러 행성의 상호작용 방정식을 풀던 중, 계수들의 조합으로 만들어지는 특성 방정식에서 행성 궤도의 '안정성 배율'을 의미하는 상수들을 찾아냈는데, 이것이 오늘날의 **고윳값**이 되었습니다.

### (3) 다비트 힐베르트와 접두사 "Eigen-"의 탄생 (1904년)
이후 수학자들은 이 개념을 행렬에 공식화했습니다. 20세기 초, 위대한 수학자 **다비트 힐베르트(David Hilbert)**는 선형 대수 수식들을 정리하며, 이 값들이 행렬 시스템이 가진 가장 "독특하고, 본질적인, 내재된" 성질이라는 의미로 독일어 형용사 *eigen*(고유한, 고집스러운)을 접두사로 붙여 **Eigenvalue(고윳값)**, **Eigenvector(고유벡터)**라 명명했고 이 이름이 오늘날 국제 표준이 되었습니다.

---

## 2. 수학적 정의와 소름 돋는 증명 과정

### (1) 근본 방정식
$n \times n$ 정방행렬 $A$가 어떤 0이 아닌 벡터 $v$와 스칼라 $\lambda$에 대해 다음 방정식을 만족할 때, $v$를 **고유벡터**, $\lambda$를 **고윳값**이라고 부릅니다.

$$ A v = \lambda v \quad (v \neq \mathbf{0}) $$

이 식의 미학은 **"우변의 복잡한 행렬곱 연산($Av$)이 좌변에서는 그저 숫자 하나 툭 곱하는 단순 스칼라 연산($\lambda v$)으로 치환된다"**는 점에 있습니다.

### (2) 유도와 증명
방정식 $Av = \lambda v$를 풀기 위해 우변의 항을 이항합니다.

$$ A v - \lambda v = \mathbf{0} $$

행렬 $A$와 스칼라 $\lambda$를 직접 뺄 수는 없으므로, 아무런 변환도 일으키지 않는 단위행렬 $I$를 도입하여 수식을 묶어줍니다.

$$ (A - \lambda I)v = \mathbf{0} $$

이 방정식이 성립하기 위해 $v = \mathbf{0}$ 이라는 해(자명한 해)를 가질 수도 있지만, 무의미한 점인 원점($\mathbf{0}$)을 제외한 **진짜 고유벡터($v \neq \mathbf{0}$)**가 존재해야 합니다.

*만약 행렬 $(A - \lambda I)$의 역행렬이 존재한다면 어떻게 될까요?*
양변의 왼쪽에 역행렬 $(A - \lambda I)^{-1}$을 곱하면 다음과 같이 강제됩니다.
$$ v = (A - \lambda I)^{-1} \mathbf{0} = \mathbf{0} $$
결국 $v = \mathbf{0}$ 이라는 무의미한 해만 남게 됩니다.

따라서 0이 아닌 진짜 고유벡터 $v$가 존재하기 위해서는 **역행렬 $(A-\lambda I)^{-1}$이 절대로 존재하면 안 됩니다.** 

행렬의 역행렬이 존재하지 않으려면 공간을 짜부라뜨려야 하므로, **행렬식(Determinant)이 정확히 0**이어야 합니다.
이를 **특성 방정식(Characteristic Equation)**이라고 합니다.

$$ \det(A - \lambda I) = 0 $$

---

## 3. 손으로 직접 푸는 구체적 2x2 예시

현재 파이토치 실습 코드에 작성된 행렬 $A$를 손으로 직접 끝까지 풀어보겠습니다.

$$ A = \begin{pmatrix} 4 & 2 \\ 1 & 3 \end{pmatrix} $$

### Step 1: 특성 행렬 $A - \lambda I$ 구하기
$$ A - \lambda I = \begin{pmatrix} 4 & 2 \\ 1 & 3 \end{pmatrix} - \begin{pmatrix} \lambda & 0 \\ 0 & \lambda \end{pmatrix} = \begin{pmatrix} 4-\lambda & 2 \\ 1 & 3-\lambda \end{pmatrix} $$

### Step 2: 행렬식 $\det(A - \lambda I) = 0$ 풀기
2x2 행렬의 행렬식 공식인 $ad - bc$를 적용합니다.
$$ \det(A - \lambda I) = (4-\lambda)(3-\lambda) - (2 \times 1) = 0 $$
$$ \lambda^2 - 7\lambda + 12 - 2 = 0 $$
$$ \lambda^2 - 7\lambda + 10 = 0 $$

인수분해를 하면 다음과 같습니다.
$$ (\lambda - 5)(\lambda - 2) = 0 $$

따라서 구하고자 하는 고윳값은 **$\lambda_1 = 5, \, \lambda_2 = 2$** 입니다. (파이토치 코드 출력과 일치합니다!)

### Step 3: 각 고윳값에 대응하는 고유벡터 $v$ 구하기

#### [경우 1] 고윳값 $\lambda_1 = 5$ 일 때
$ (A - 5I)v = \mathbf{0} $ 식에 벡터 $v = \begin{pmatrix} x \\ y \end{pmatrix}$ 를 대입합니다.
$$ \begin{pmatrix} 4-5 & 2 \\ 1 & 3-5 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} -1 & 2 \\ 1 & -2 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix} $$

이 연립방정식을 연산하면 다음과 같습니다.
$$ -x + 2y = 0 \implies x = 2y $$

고유벡터는 축의 '방향'을 의미하므로 무수히 많은 크기가 존재합니다. 가장 대표적인 정수 비율 비로 나타내면 $y=1$ 일 때 $x=2$ 가 되므로:
$$ v_1 = \begin{pmatrix} 2 \\ 1 \end{pmatrix} \quad (\text{또는 크기가 1이 되도록 정규화한 벡터}) $$

#### [경우 2] 고윳값 $\lambda_2 = 2$ 일 때
$ (A - 2I)v = \mathbf{0} $ 식에 벡터 $v = \begin{pmatrix} x \\ y \end{pmatrix}$ 를 대입합니다.
$$ \begin{pmatrix} 4-2 & 2 \\ 1 & 3-2 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 2 & 2 \\ 1 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix} $$

이 연립방정식을 연산하면 다음과 같습니다.
$$ x + y = 0 \implies x = -y $$

이것도 가장 대표적인 정수 비율 비로 잡기 위해 $y=-1$ 일 때 $x=1$ 로 잡으면:
$$ v_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix} $$

*(💡 참고: 파이토치와 임포트된 수학 라이브러리들은 선형 공간 조작의 표준을 따르기 위해 고유벡터 $v$의 길이를 모두 **1**로 컴퓨터가 강제 다운스케일링(L2 Normalization)하여 출력합니다. 실제 코드 셀의 고유벡터 출력값 $[-0.89, -0.44]$ 등을 보면 $[-2/\sqrt{5}, -1/\sqrt{5}]$ 로 방향 보존성(비율 $2:1$)은 일치합니다.)*

In [2]:
import torch

# 1. 행렬 A 선언 
A = torch.tensor([[4.0, 2.0],
                  [1.0, 3.0]], dtype=torch.float32)

# 2. 고윳값과 고유벡터 계산
eigenvalues, eigenvectors = torch.linalg.eig(A)
eigenvalues = eigenvalues.real
eigenvectors = eigenvectors.real

print("===== 100% 손으로 푼 수식의 결과와 PyTorch의 방향 일치 확인 =====")

# 손으로 구한 고유벡터와 파이토치의 고유벡터 비교하기
# 파이토치의 첫 번째 고유벡터 (길이가 1로 정규화됨)
v1_torch = eigenvectors[:, 0].unsqueeze(1)
# 비율이 2:1 인지 확인 (x를 y로 나눴을 때 2가 나오는지 확인)
print(f"PyTorch v1 비율 [x/y]: {v1_torch[0].item() / v1_torch[1].item():.1f} (손 계산인 2:1과 완벽 일치!)")

# 파이토치의 두 번째 고유벡터 
v2_torch = eigenvectors[:, 1].unsqueeze(1)
# 비율이 1:-1 인지 확인 
print(f"PyTorch v2 비율 [x/y]: {v2_torch[0].item() / v2_torch[1].item():.1f} (손 계산인 1:-1과 완벽 일치!)")


print("\n===== 검증 (Av = λv) =====")
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i].unsqueeze(1)
    
    left = torch.matmul(A, v)
    right = lam * v
    
    print(f"\n[고윳값 λ = {lam.item():.1f}]")
    print(f"A * v  :\n{left.numpy()}")
    print(f"λ * v  :\n{right.numpy()}")
    print(f"두 연산이 수학적으로 동일한가? : {torch.allclose(left, right)}")

===== 100% 손으로 푼 수식의 결과와 PyTorch의 방향 일치 확인 =====
PyTorch v1 비율 [x/y]: 2.0 (손 계산인 2:1과 완벽 일치!)
PyTorch v2 비율 [x/y]: -1.0 (손 계산인 1:-1과 완벽 일치!)

===== 검증 (Av = λv) =====

[고윳값 λ = 5.0]
A * v  :
[[4.4721365]
 [2.2360682]]
λ * v  :
[[4.472136 ]
 [2.2360682]]
두 연산이 수학적으로 동일한가? : True

[고윳값 λ = 2.0]
A * v  :
[[-1.4142138]
 [ 1.4142134]]
λ * v  :
[[-1.4142135]
 [ 1.4142134]]
두 연산이 수학적으로 동일한가? : True


In [6]:
# 고유값 벡터 
import numpy as np

a = np.array([[0,1], [-2, -3]]) #고유값과 고유벡터 계산
print(np.linalg.eig(a)[0]) #고유 벡터 
print(np.linalg.eig(a)[1]) #고유 벡터 

[-1. -2.]
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [4]:
np.array([[1,-1]])/ np.sqrt((np.array([1,-1])**2).sum())

array([[ 0.70710678, -0.70710678]])

In [5]:
np.array([-1, 2])/np.sqrt((np.array([-1, 2])**2).sum())

array([-0.4472136 ,  0.89442719])