# PCA와 특이값분해(SVD)는 실제 문제에서 어떻게 쓰일까?

핵심부터 정리하면 다음과 같습니다.

**PCA는 “변수들이 어떤 방향으로 함께 움직이는가”를 찾는 분석법**이고,  
**SVD는 행렬 안의 큰 패턴부터 작은 패턴까지 분해해서 압축, 추천, 노이즈 제거 등에 쓰는 계산법**입니다.

둘은 실제로 매우 가깝습니다.

중심화된 데이터 행렬을 $X$라고 하면,

$$
X = U\Sigma V^\top
$$

이고 PCA에서는 다음과 같이 해석합니다.

$$
V = \text{주성분 방향}
$$

$$
U\Sigma = \text{각 데이터의 PCA 점수}
$$

$$
\frac{\sigma_i^2}{n-1} = \text{각 주성분의 분산}
$$

---

# 1. 실제 분석에서 PCA는 무엇을 하는가?

예를 들어 고객 데이터가 있다고 해봅시다.

| 고객 | 월방문수 | 구매금액 | 쿠폰사용수 |
|---:|---:|---:|---:|
| 1 | 2 | 7 | 8 |
| 2 | 3 | 9 | 7 |
| 3 | 4 | 13 | 2 |
| 4 | 5 | 15 | 3 |
| 5 | 7 | 18 | 9 |
| 6 | 8 | 24 | 1 |
| 7 | 9 | 25 | 5 |
| 8 | 10 | 28 | 2 |
| 9 | 12 | 34 | 6 |
| 10 | 13 | 37 | 1 |

변수는 3개입니다.

$$
x_1 = \text{월방문수}
$$

$$
x_2 = \text{구매금액}
$$

$$
x_3 = \text{쿠폰사용수}
$$

이 데이터를 그냥 보면 세 변수를 동시에 해석해야 합니다.

PCA는 이 세 변수를 더 적은 수의 새 축으로 바꿔줍니다.

---

# 2. PCA 실제 처리 순서

실제 분석에서는 보통 다음 순서로 PCA를 적용합니다.

$$
\text{원본 데이터}
\rightarrow
\text{평균 중심화}
\rightarrow
\text{필요하면 표준화}
\rightarrow
\text{공분산 또는 상관 구조 계산}
\rightarrow
\text{주성분 방향 계산}
\rightarrow
\text{데이터를 주성분 점수로 변환}
$$

여기서는 변수 단위가 다릅니다.

월방문수는 2~13 정도이고, 구매금액은 7~37 정도이고, 쿠폰사용수는 1~9 정도입니다.

단위가 다르면 숫자 스케일이 큰 변수가 PCA를 지배할 수 있으므로 보통 표준화합니다.

표준화는 각 변수에 대해 다음 값을 계산하는 것입니다.

$$
z = \frac{x-\bar{x}}{s}
$$

즉, 평균을 빼고 표준편차로 나눕니다.

---

# 3. PCA 결과 예시

이 데이터를 표준화한 뒤 PCA를 하면 다음과 같은 결과가 나왔다고 합시다.

첫 번째 주성분:

$$
PC_1 = 0.634(\text{월방문수}) + 0.645(\text{구매금액}) - 0.426(\text{쿠폰사용수})
$$

두 번째 주성분:

$$
PC_2 = 0.339(\text{월방문수}) + 0.263(\text{구매금액}) + 0.903(\text{쿠폰사용수})
$$

여기서 \(0.634, 0.645, -0.426\) 같은 값들이 바로 고유벡터의 성분, 즉 **loading**입니다.

이 값들은 원본 데이터에서 그냥 가져온 값이 아닙니다.

원본 데이터의 공분산 또는 상관 구조를 계산한 뒤 거기서 도출된 값입니다.

---

# 4. 첫 번째 주성분은 어떻게 해석하나?

$$
PC_1 = 0.634(\text{월방문수}) + 0.645(\text{구매금액}) - 0.426(\text{쿠폰사용수})
$$

이 식을 보면 월방문수와 구매금액은 양수입니다.

$$
0.634 > 0,\quad 0.645 > 0
$$

쿠폰사용수는 음수입니다.

$$
-0.426 < 0
$$

따라서 \(PC_1\)이 높은 고객은 대체로 다음 성격을 가집니다.

$$
\text{방문이 많고, 구매금액이 크고, 쿠폰 의존도는 낮은 고객}
$$

즉, \(PC_1\)은 대략 **고객의 순수 활동성 또는 고가치 고객성**으로 해석할 수 있습니다.

반대로 \(PC_1\)이 낮으면 방문도 적고 구매금액도 낮으며, 상대적으로 쿠폰 의존도가 큰 고객일 가능성이 있습니다.

---

# 5. 두 번째 주성분은 어떻게 해석하나?

$$
PC_2 = 0.339(\text{월방문수}) + 0.263(\text{구매금액}) + 0.903(\text{쿠폰사용수})
$$

여기서는 쿠폰사용수의 계수가 압도적으로 큽니다.

$$
0.903
$$

따라서 \(PC_2\)는 대략 **쿠폰 반응성 또는 프로모션 민감도**로 해석할 수 있습니다.

즉, \(PC_2\)가 높은 고객은 방문수나 구매금액보다 쿠폰사용 성향이 강하게 나타나는 고객입니다.

---

# 6. 설명분산비율을 본다

PCA에서는 각 주성분이 전체 데이터의 변동을 얼마나 설명하는지도 봅니다.

이 예제에서는 대략 다음과 같은 결과가 나옵니다.

| 주성분 | 설명분산비율 | 해석 |
|---:|---:|---|
| PC1 | 76.0% | 고가치/활동성 축 |
| PC2 | 23.9% | 쿠폰 반응성 축 |
| PC3 | 0.1% | 거의 의미 없는 잔여 축 |

즉, 원래 변수는 3개였지만 앞의 두 주성분만으로 다음 정도의 정보를 설명합니다.

$$
76.0\% + 23.9\% = 99.9\%
$$

그래서 이 데이터는 3차원이지만 사실상 2차원으로 줄여도 거의 손실이 없습니다.

---

# 7. PCA 점수는 실제로 어떻게 쓰나?

각 고객을 원래의 세 변수 대신 \(PC_1, PC_2\) 점수로 표현할 수 있습니다.

예를 들어 일부 고객의 PCA 점수가 다음처럼 나왔다고 합시다.

| 고객 | PC1 점수 | PC2 점수 | 해석 |
|---:|---:|---:|---|
| 고객 1 | -2.28 | 0.25 | 활동성 낮고 쿠폰 성향 약간 있음 |
| 고객 3 | -0.72 | -1.23 | 활동성 낮고 쿠폰 의존도도 낮음 |
| 고객 5 | -0.90 | 1.29 | 활동성은 낮은 편이나 쿠폰 반응이 큼 |
| 고객 10 | 2.45 | -0.10 | 활동성·구매금액 높고 쿠폰 의존도 낮음 |

이제 마케팅 담당자는 이렇게 쓸 수 있습니다.

고객 10은 \(PC_1\)이 높습니다.  
즉, 방문도 많고 구매금액도 큰 고가치 고객입니다. 쿠폰을 많이 주지 않아도 구매할 가능성이 높습니다.

고객 5는 \(PC_2\)가 높습니다.  
즉, 쿠폰에 민감한 고객입니다. 프로모션 캠페인 대상자로 적합할 수 있습니다.

고객 3은 \(PC_1\), \(PC_2\)가 모두 낮습니다.  
즉, 활동성도 낮고 쿠폰 반응도 낮은 고객입니다. 단순 쿠폰보다 다른 재활성화 전략이 필요할 수 있습니다.

---

# 8. PCA가 실제 문제에서 쓰이는 방식

PCA는 실제로 다음과 같은 문제에 쓰입니다.

## 8.1. 시각화

원래 변수가 50개, 100개라면 사람이 볼 수 없습니다.

PCA로 \(PC_1, PC_2\) 두 축만 뽑으면 2차원 그래프로 볼 수 있습니다.

예를 들어 고객을 \(PC_1\)-\(PC_2\) 평면에 찍으면 다음과 같은 군집이 보일 수 있습니다.

$$
\text{고가치 고객군}
$$

$$
\text{쿠폰 민감 고객군}
$$

$$
\text{저활동 고객군}
$$

---

## 8.2. 차원축소

원래 변수가 100개인데 앞의 10개 주성분이 전체 분산의 95%를 설명한다면, 100개 변수를 10개 숫자로 줄일 수 있습니다.

$$
100\text{차원} \rightarrow 10\text{차원}
$$

이렇게 하면 모델 학습이 빨라지고, 노이즈가 줄고, 과적합이 줄 수 있습니다.

---

## 8.3. 노이즈 제거

작은 고유값에 해당하는 주성분은 데이터의 주요 구조보다 잡음일 수 있습니다.

그래서 큰 주성분만 남기고 작은 주성분은 버리면 데이터가 부드러워집니다.

---

## 8.4. 특징 생성

원래 변수들을 그대로 쓰는 대신,

$$
PC_1, PC_2, PC_3
$$

를 머신러닝 모델의 입력으로 넣을 수 있습니다.

---

# 9. 이제 SVD는 실제로 어떻게 쓰이나?

SVD는 행렬을 다음처럼 분해합니다.

$$
X = U\Sigma V^\top
$$

이것을 펼쳐 쓰면,

$$
X =
\sigma_1 u_1v_1^\top
+
\sigma_2 u_2v_2^\top
+
\sigma_3 u_3v_3^\top
+
\cdots
$$

입니다.

즉, 데이터 행렬을 여러 개의 패턴으로 나눕니다.

$$
\sigma_1 u_1v_1^\top = \text{가장 큰 패턴}
$$

$$
\sigma_2 u_2v_2^\top = \text{두 번째로 큰 패턴}
$$

$$
\sigma_3 u_3v_3^\top = \text{세 번째 패턴}
$$

입니다.

특이값이 클수록 중요한 패턴입니다.

---

# 10. SVD와 PCA의 정확한 관계

PCA에서 중심화된 데이터 행렬을 \(X\)라고 하면,

$$
X = U\Sigma V^\top
$$

입니다.

그러면 공분산행렬은 다음과 같습니다.

$$
C = \frac{1}{n-1}X^\top X
$$

SVD를 대입하면,

$$
X^\top X = V\Sigma^2V^\top
$$

이므로,

$$
C = V\frac{\Sigma^2}{n-1}V^\top
$$

입니다.

따라서 PCA에서 쓰는 값들은 SVD에서 바로 나옵니다.

$$
\boxed{V = \text{PCA 주성분 방향}}
$$

$$
\boxed{U\Sigma = \text{PCA 점수}}
$$

$$
\boxed{\lambda_i = \frac{\sigma_i^2}{n-1}}
$$

$$
\boxed{\text{설명분산비율} = \frac{\sigma_i^2}{\sum_j \sigma_j^2}}
$$

즉, 실제 계산에서는 PCA를 고유값분해로 설명하지만, 구현은 SVD로 하는 경우가 많습니다.

---

# 11. SVD 예제 1: 추천 시스템

영화 평점 행렬이 있다고 해봅시다.

행은 사용자, 열은 영화입니다.

| 사용자 | 영화 A | 영화 B | 영화 C | 영화 D |
|---:|---:|---:|---:|---:|
| 사용자 1 | 5 | 5 | 1 | 1 |
| 사용자 2 | 4 | 5 | 1 | 0 |
| 사용자 3 | 5 | 4 | 0 | 1 |
| 사용자 4 | 1 | 0 | 5 | 5 |
| 사용자 5 | 0 | 1 | 4 | 5 |
| 사용자 6 | 1 | 1 | 5 | 4 |

눈으로 보면 사용자 1, 2, 3은 영화 A, B를 좋아합니다.  
사용자 4, 5, 6은 영화 C, D를 좋아합니다.

SVD는 이 행렬에서 이런 잠재 패턴을 찾아냅니다.|

예를 들어 특이값이 다음처럼 나왔다고 합시다.

| 순서 | 특이값 | 의미 |
|---:|---:|---|
| \(\sigma_1\) | 13.10 | 전체적인 평점 크기 |
| \(\sigma_2\) | 9.82 | A/B 취향과 C/D 취향을 가르는 축 |
| \(\sigma_3\) | 1.58 | 작은 세부 차이 |
| \(\sigma_4\) | 1.22 | 작은 세부 차이 |

여기서 앞의 두 특이값이 큽니다.

$$
13.10,\quad 9.82
$$

따라서 이 평점 행렬의 주요 구조는 사실상 두 가지입니다.

첫 번째 패턴:

$$
\text{전체적으로 평점을 얼마나 많이 주는가}
$$

두 번째 패턴:

$$
\text{영화 A/B를 좋아하는가, 영화 C/D를 좋아하는가}
$$

---

# 12. 추천 시스템에서 \(V^\top\)는 무엇을 의미하나?

SVD 결과에서 \(V^\top\)의 앞 두 행이 대략 다음처럼 나왔다고 합시다.

$$
(V^\top)_1 \approx
\begin{bmatrix}0.50 & 0.50 & 0.50 & 0.50\end{bmatrix}
$$

$$
(V^\top)_2 \approx
\begin{bmatrix}0.50 & 0.50 & -0.50 & -0.50\end{bmatrix}
$$

첫 번째 축은 모든 영화에 비슷하게 양수입니다.

$$
\begin{bmatrix}0.50 & 0.50 & 0.50 & 0.50\end{bmatrix}
$$

그래서 이것은 **전체적인 평점 수준**입니다.

두 번째 축은 영화 A, B는 양수이고 영화 C, D는 음수입니다.

$$
\begin{bmatrix}0.50 & 0.50 & -0.50 & -0.50\end{bmatrix}
$$

그래서 이것은 **A/B 취향 대 C/D 취향**입니다.

즉, SVD는 영화들을 보이지 않는 잠재 취향 축에 배치합니다.

---

# 13. 추천 시스템에서 \(U\Sigma\)는 무엇을 의미하나?

사용자들의 점수가 대략 다음처럼 나왔다고 합시다.

| 사용자 | 잠재축 1 | 잠재축 2 | 해석 |
|---:|---:|---:|---|
| 사용자 1 | 6.00 | 4.00 | A/B 취향 강함 |
| 사용자 2 | 5.00 | 4.01 | A/B 취향 강함 |
| 사용자 3 | 5.00 | 3.99 | A/B 취향 강함 |
| 사용자 4 | 5.50 | -4.50 | C/D 취향 강함 |
| 사용자 5 | 5.00 | -4.00 | C/D 취향 강함 |
| 사용자 6 | 5.50 | -3.50 | C/D 취향 강함 |

여기서 두 번째 축이 양수이면 A/B 취향입니다.

두 번째 축이 음수이면 C/D 취향입니다.

그래서 사용자 1에게는 영화 A, B와 비슷한 영화가 추천될 수 있고, 사용자 4에게는 영화 C, D와 비슷한 영화가 추천될 수 있습니다.

실제 추천 시스템에서는 결측 평점을 직접 다루기 위해 추가적인 최적화나 행렬완성 방법을 쓰지만, 기본 아이디어는 같습니다.

$$
\text{사용자-아이템 행렬}
\rightarrow
\text{SVD 또는 행렬분해}
\rightarrow
\text{사용자 잠재벡터와 아이템 잠재벡터}
\rightarrow
\text{내적으로 선호도 예측}
$$

예측 평점은 대략 이렇게 계산합니다.

$$
\hat{r}_{ui} = \text{사용자 }u\text{의 잠재벡터} \cdot \text{아이템 }i\text{의 잠재벡터}
$$

---

# 14. SVD 예제 2: 이미지 압축

흑백 이미지는 숫자 행렬입니다.

예를 들어 1000×1000 흑백 이미지는 다음과 같은 행렬입니다.

$$
A \in \mathbb{R}^{1000 \times 1000}
$$

각 원소는 픽셀 밝기입니다.

SVD를 하면,

$$
A = U\Sigma V^\top
$$

입니다.

이때 특이값이 다음처럼 나온다고 합시다.

$$
\sigma_1 = 5000
$$

$$
\sigma_2 = 1200
$$

$$
\sigma_3 = 300
$$

$$
\sigma_4 = 80
$$

$$
\sigma_5 = 20
$$

앞의 몇 개 특이값이 대부분의 정보를 담고 있다면, 뒤의 작은 특이값들은 버릴 수 있습니다.

원래 이미지는 다음과 같이 표현됩니다.

$$
A =
\sigma_1u_1v_1^\top
+
\sigma_2u_2v_2^\top
+
\cdots
+
\sigma_{1000}u_{1000}v_{1000}^\top
$$

하지만 앞의 \(k\)개만 남겨서 다음처럼 근사합니다.

$$
A_k =
\sigma_1u_1v_1^\top
+
\cdots
+
\sigma_ku_kv_k^\top
$$

예를 들어 \(k=50\)만 써도 원본 이미지가 꽤 비슷하게 보일 수 있습니다.

이게 이미지 압축입니다.

원본 저장량은 대략 다음과 같습니다.

$$
1000 \times 1000 = 1,000,000
$$

즉, 숫자 1,000,000개가 필요합니다.

하지만 \(k=50\) SVD 근사를 쓰면 필요한 숫자는 대략 다음과 같습니다.

$$
U_k: 1000 \times 50
$$

$$
\Sigma_k: 50
$$

$$
V_k^\top: 50 \times 1000
$$

따라서 저장해야 하는 숫자는 다음 정도입니다.

$$
50,000 + 50 + 50,000 = 100,050
$$

원래 1,000,000개에서 약 100,050개로 줄어듭니다.

즉, 약 10분의 1 수준으로 압축할 수 있습니다.

---

# 15. SVD 예제 3: 문서 분석

문서-단어 행렬도 SVD를 쓸 수 있습니다.

예를 들어 행은 문서, 열은 단어입니다.

| 문서 | 주식 | 투자 | 금리 | 축구 | 경기 | 선수 |
|---:|---:|---:|---:|---:|---:|---:|
| 문서 1 | 5 | 4 | 3 | 0 | 0 | 0 |
| 문서 2 | 4 | 5 | 2 | 0 | 0 | 0 |
| 문서 3 | 0 | 0 | 0 | 5 | 4 | 5 |
| 문서 4 | 0 | 0 | 0 | 4 | 5 | 4 |

이 행렬에 SVD를 적용하면 주요 패턴이 나옵니다.

첫 번째 잠재축은 금융 관련 단어들을 묶을 수 있습니다.

$$
\text{주식, 투자, 금리}
$$

두 번째 잠재축은 스포츠 관련 단어들을 묶을 수 있습니다.

$$
\text{축구, 경기, 선수}
$$

그래서 SVD는 문서들을 주제 공간으로 바꾸는 데 쓰입니다.

$$
\text{문서-단어 행렬}
\rightarrow
\text{SVD}
\rightarrow
\text{잠재 주제}
$$

이 방식은 **LSA, Latent Semantic Analysis**의 기본 아이디어입니다.

---

# 16. PCA와 SVD를 실제로 언제 쓰는가?

## 16.1. PCA를 쓰기 좋은 경우

PCA는 보통 이런 문제에 씁니다.

$$
\text{변수가 너무 많을 때}
$$

$$
\text{변수들이 서로 강하게 상관되어 있을 때}
$$

$$
\text{데이터를 2D 또는 3D로 시각화하고 싶을 때}
$$

$$
\text{노이즈를 줄이고 싶을 때}
$$

예를 들어 유전자 데이터는 변수 수가 수천 개일 수 있습니다.

PCA로 줄이면 샘플들이 어떤 그룹으로 나뉘는지 볼 수 있습니다.

예를 들어 제조 센서 데이터도 센서가 수십 개일 수 있습니다.

PCA로 정상 작동 패턴을 찾고, 주성분 공간에서 멀리 떨어진 점을 이상치로 볼 수 있습니다.

---

## 16.2. SVD를 쓰기 좋은 경우

SVD는 보통 이런 문제에 씁니다.

$$
\text{행렬 압축}
$$

$$
\text{추천 시스템}
$$

$$
\text{이미지 압축}
$$

$$
\text{문서-단어 잠재 의미 분석}
$$

$$
\text{노이즈 제거}
$$

$$
\text{PCA 계산}
$$

SVD는 **행렬 안의 큰 구조부터 꺼내는 도구**라고 보면 됩니다.

---

# 17. PCA와 SVD의 차이를 직관적으로 정리

PCA는 질문이 통계적입니다.

> 데이터가 가장 많이 퍼져 있는 방향은 어디인가?

SVD는 질문이 선형대수적입니다.

> 이 행렬을 가장 중요한 패턴들의 합으로 어떻게 쪼갤 수 있는가?

하지만 중심화된 데이터 행렬에 대해서는 두 질문이 같은 방향으로 만납니다.

$$
X = U\Sigma V^\top
$$

에서 \(V\)가 PCA의 주성분 방향이고,

$$
U\Sigma
$$

가 PCA 점수입니다.

---

# 18. 실제 분석자가 보는 핵심 값들

PCA/SVD 결과에서 실제로 보는 값은 보통 네 가지입니다.

## 18.1. 주성분 방향 또는 loading

예를 들어 다음과 같은 식을 봅니다.

$$
PC_1 = 0.634x_1 + 0.645x_2 - 0.426x_3
$$

이걸 보고 PC1이 어떤 의미인지 해석합니다.

---

## 18.2. 설명분산비율

예를 들어 다음 값을 봅니다.

$$
PC_1 = 76.0\%,\quad PC_2 = 23.9\%
$$

이걸 보고 몇 개의 주성분을 남길지 결정합니다.

---

## 18.3. 점수, 즉 score

PCA 점수는 다음과 같이 계산합니다.

$$
Z = XV
$$

각 데이터가 새 축에서 어디에 있는지 봅니다.

고객 분석에서는 고객군 분류, 이상치 탐지, 시각화에 씁니다.

---

## 18.4. 특이값

SVD에서는 특이값을 봅니다.

$$
\sigma_1,\sigma_2,\dots
$$

큰 특이값은 중요한 패턴이고, 작은 특이값은 덜 중요한 패턴입니다.

이미지 압축, 추천 시스템, 노이즈 제거에서는 특이값을 보고 몇 개의 패턴을 남길지 결정합니다.

---

# 19. 한 줄 요약

PCA는 원본 변수들을 새 축으로 바꿔서 **데이터의 중요한 방향을 해석하고 차원을 줄이는 방법**입니다.

SVD는 행렬을 중요한 패턴 순서대로 분해해서 **PCA 계산, 압축, 추천, 문서 분석, 노이즈 제거에 쓰는 방법**입니다.

둘의 연결은 이것입니다.

$$
\boxed{ X = U\Sigma V^\top }
$$

$$
\boxed{ V = \text{PCA의 주성분 방향} }
$$

$$
\boxed{ U\Sigma = \text{PCA 점수} }
$$

$$
\boxed{ \frac{\sigma_i^2}{n-1} = \text{PCA의 주성분 분산} }
$$

즉, 실제 문제에서는 PCA와 SVD를 통해 복잡한 데이터를 **적은 수의 의미 있는 축과 패턴**으로 바꿔 분석합니다.

In [13]:
from scipy.linalg import svd 
import numpy as np
a = np.array([[3,2,2], [2,3,-2]])
display(a)
u,s,vt = svd(a)
display(u) # Left singular vectors
display(s) # Singular values
display(vt) # Right singular vectors, not v, v_T

display( np.linalg.eig(a.T @ a )[0]) # Eigenvalues of A^T A, 고유값 벡터 
# U, V is unitary matrix, so U^T U = I, V^T V = I
display( np.round(u.T @ u, 10) ) # U^T U = I
display( np.round(vt @ vt.T, 10) ) # V^T V = I 10^-9 의 경우 0으로 취급하기 때문에 
# I is unitary matrix, so I^T I = I

array([[ 3,  2,  2],
       [ 2,  3, -2]])

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

array([5., 3.])

array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

array([2.5000000e+01, 5.0324328e-15, 9.0000000e+00])

array([[1., 0.],
       [0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
S = np.zeros((2,3))
display(S)
display(s) #Singular values
S[0,0], S[1,1] = s #svd 함수는 행렬 A의 singular values를 1차원 배열로 반환하기 때문에, S 행렬에 대입하기 위해서는 인덱싱이 필요하다. 
print(S) 
A = u @ S @ vt # A = U S V^T
display(A) # A = U S V^T


array([[0., 0., 0.],
       [0., 0., 0.]])

array([5., 3.])

[[5. 0. 0.]
 [0. 3. 0.]]


array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

## 특잇값 분해의 용도 

- sklearn PCA클래스는 내부적으로 특잇값 분해를 활용 
- 심층학습에서 무어-펜로즈 유사 역행렬(pseudoinverse)을 계산

### 주성분 분석을 위한 특잇값 분해 

$$ 
X = U\Sigma V^\top
$$

- $\Sigma 와 V^\top $ 을 원하는 개수의 가장 큰 특잇값만 남기고 축소.
- svd 함수는 $\Sigma$의 대각 성분들을 돌려줌

In [19]:
from sklearn.datasets import load_iris
iris = load_iris().data.copy() # iris.data is read-only, so copy() is needed
m = iris.mean(axis=0)
ir = iris - m # Centering the data
u,s,vt = svd(ir)

In [ ]:
S = np.zeros((ir.shape[0], ir.shape[1]))
for i in range(4):
    S[i,i] = s[i]
S = S[:, :2] # 4x2 matrix
T = u @ S # 150x2 matrix, projection onto the first 2 principal components
display(S)
display(T) # 150x2 matrix

array([[25.09996044,  0.        ],
       [ 0.        ,  6.01314738],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,

array([[-2.68412563, -0.31939725],
       [-2.71414169,  0.17700123],
       [-2.88899057,  0.14494943],
       [-2.74534286,  0.31829898],
       [-2.72871654, -0.32675451],
       [-2.28085963, -0.74133045],
       [-2.82053775,  0.08946138],
       [-2.62614497, -0.16338496],
       [-2.88638273,  0.57831175],
       [-2.6727558 ,  0.11377425],
       [-2.50694709, -0.6450689 ],
       [-2.61275523, -0.01472994],
       [-2.78610927,  0.235112  ],
       [-3.22380374,  0.51139459],
       [-2.64475039, -1.17876464],
       [-2.38603903, -1.33806233],
       [-2.62352788, -0.81067951],
       [-2.64829671, -0.31184914],
       [-2.19982032, -0.87283904],
       [-2.5879864 , -0.51356031],
       [-2.31025622, -0.39134594],
       [-2.54370523, -0.43299606],
       [-3.21593942, -0.13346807],
       [-2.30273318, -0.09870885],
       [-2.35575405,  0.03728186],
       [-2.50666891,  0.14601688],
       [-2.46882007, -0.13095149],
       [-2.56231991, -0.36771886],
       [-2.63953472,

# 무어-펜로즈 유사역행렬(Moore-Penrose pseudoinverse)

- "역행렬이 없는 행렬에도, 가장 그럴듯한 역연산을 해주는 도구"

In [22]:
import numpy as np

# -----------------------------------
# 1) 정방행렬이 아닌 경우(2x3): 일반 역행렬 inv(A)는 없음
# -----------------------------------
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=float)

print("A shape:", A.shape)

# 일반 역행렬은 정방행렬에서만 가능 -> 여기서는 불가능
# np.linalg.inv(A)  # 오류 발생

# 유사역행렬은 가능
A_pinv = np.linalg.pinv(A)
print("A^+ shape:", A_pinv.shape)
print("A^+ =\n", A_pinv)

# -----------------------------------
# 2) 유사역행렬의 대표 성질 확인
#    A A^+ A = A
#    A^+ A A^+ = A^+
# -----------------------------------
left1 = A @ A_pinv @ A
left2 = A_pinv @ A @ A_pinv

print("\nA @ A^+ @ A ≈ A ? ->", np.allclose(left1, A))
print("A^+ @ A @ A^+ ≈ A^+ ? ->", np.allclose(left2, A_pinv))

# -----------------------------------
# 3) 최소제곱 해(과결정 시스템) 예제
#    Ax = b를 정확히 못 맞춰도, 오차가 최소인 x를 구함
# -----------------------------------
B = np.array([
    [1, 1],
    [1, 2],
    [1, 3]
], dtype=float)   # 3x2 (식 3개, 미지수 2개)

b = np.array([1, 2, 2.8], dtype=float)

# 최소제곱 해 x* = B^+ b
x_star = np.linalg.pinv(B) @ b

print("\nLeast-squares solution x* =", x_star)

# 예측값과 오차 확인
b_hat = B @ x_star
residual = b - b_hat

print("predicted b_hat =", b_hat)
print("residual =", residual)
print("residual norm =", np.linalg.norm(residual))

A shape: (2, 3)
A^+ shape: (3, 2)
A^+ =
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

A @ A^+ @ A ≈ A ? -> True
A^+ @ A @ A^+ ≈ A^+ ? -> True

Least-squares solution x* = [0.13333333 0.9       ]
predicted b_hat = [1.03333333 1.93333333 2.83333333]
residual = [-0.03333333  0.06666667 -0.03333333]
residual norm = 0.08164965809277286


1. 정방행렬이 아니어도 `pinv`는 계산 가능
2. `A @ A^+ @ A ≈ A` 성질로 "역연산 역할"을 확인 가능
3. `x* = A^+ b`는 최소제곱 해를 빠르게 줌

---

역사 요약:
1. E. H. Moore(1920): 일반화된 역연산 개념을 제시
2. Roger Penrose(1955): 4가지 조건(현재의 Moore-Penrose 조건)을 정식화
3. 이후 SVD(특잇값분해) 기반 계산법이 널리 정착되며 실무 표준이 됨

Penrose의 4조건(개념적으로):
1. \(AA^+A = A\)
2. \(A^+AA^+ = A^+\)
3. \((AA^+)^\top = AA^+\)
4. \((A^+A)^\top = A^+A\)

---

어디에 쓰는가:
1. 최소제곱 회귀: 선형회귀의 해를 \(x = A^+b\)로 계산
2. 신호처리/통신: 노이즈 환경에서 안정적 추정
3. 제어/로보틱스: 자코비안 역문제(로봇 관절 속도 계산)
4. 컴퓨터비전: 카메라 보정, 좌표 복원
5. 머신러닝: 랭크 부족(rank-deficient) 데이터의 해 안정화
6. 딥러닝 이론/최적화: 선형 근사, 저차원 해석, 가중치 해석에 활용

원하면 다음 답변에서
1. SVD로 \(A^+\)를 손으로 만드는 과정
2. 왜 작은 특잇값에서 수치 불안정이 생기는지
3. 현재 노트북 흐름(SVD/PCA)에 맞춘 맞춤형 셀 예제  
까지 이어서 만들어드릴게요.